### ISSUE TITLE
网页版终端无法打开

### ISSUE THREAD

**Issue by Payton443** [IceWhaleTech/ZimaOS#104]
从1.2.2版本升级到1.2.4版本后，打开 系统设置-安全-启用SSH访问后，下方的网页版终端(7680)无法打开，Edge浏览器提示：
嗯… 无法访问此页面
x.x.x.x 已拒绝连接。
请尝试：......

**Comment by LinkLeong** [comment]
很抱歉，由于我们的工作流程问题，这个功能在发布的时候出现了问题，会在最新版带上该功能。

**Comment by LinkLeong** [comment]
Our 1.2.5 has been released and is ready for testing.
