### ISSUE TITLE
Manually Updating Wireguard Easy?

### ISSUE THREAD

**Issue by ketoeater** [IceWhaleTech/ZimaOS#105]
Do I have to wait for the container to be updated in the App Store or can I follow manual update procedures outlined here: https://github.com/wg-easy/wg-easy#updating

`docker stop wg-easy`
`docker rm wg-easy`
`docker pull ghcr.io/wg-easy/wg-easy`

The app is displaying an alert that an update is available:

![image](https://github.com/user-attachments/assets/38c66119-c8b8-490d-9677-daddb850ffc9)

**Comment by CorrectRoadH** [comment]
to wait the App Store update is a good idea. if you want to manually update WE. a way is change the tag in Settings

https://github.com/user-attachments/assets/b6f7b0d9-aec3-487a-ac27-cfead8c9fa83

**Comment by LinkLeong** [comment]
We will close the question, and if you have any questions, you can reopen it.
