### ISSUE TITLE
Initial user creation fails on installation of V1.2.5 on PROXMOX

### ISSUE THREAD

**Issue by dhedman** [IceWhaleTech/ZimaOS#108]
I followed the instructions to install ZimaOS on PROXMOX.
ZimaOS=V1.2.5
PROXMOX=V8.2.2

After installation, I was not able to create an initial userid on the first screen. All I  received was a fail message with no other context.

My initial install was V1.2.1 and then I realized that was outdated. In that attempt the apps would fail to load and display. I removed the disk from my initial PROXMOX attempt, imported the latest V1.2.5 into the VM. At this point I was unable to create the userid on the first screen, so I logged into the Zima install and found that root was at 100%, which would prevent the user creation. I looked around and noticed there was a large file in: /DATA/rauc/releases/v1.2.5. 

It was: zima0s_zimacube-1.2.5.raucb.  I then 
I looking at the documentation, I saw that was an image for upgrading a current systems less than V1.2.5, so I took a chance and removed it. I then brought up the login screen again, and I was able to create the user, but still do not have the ability load the apps. It just tells me they failed and to refresh later. This was in fact the same issue I had with V1.2.1 on my original install

In searching the web, I have seen the issue raised before but I have yet to locate a resolution for this issue. Did I just miss it or is it ongoing?

I do see that the / root slice is still at 100% but at least /DATA is no longer 100%
root@ZimaCube:/DATA/rauc/releases/v1.2.5# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       4.3G  4.3G     0 100% /
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           785M   12M  773M   2% /run
tmpfs           2.0G  112K  2.0G   1% /tmp
tmpfs           2.0G  2.3M  2.0G   1% /var
/dev/sda1        32M  712K   32M   3% /mnt/boot
/dev/sda7        85M  736K   78M   1% /mnt/overlay
/dev/sda8        70M  3.4M   61M   6% /DATA

I did double check and secure boot is still turned off.

**Comment by dhedman** [comment]
a follow up:

the /etc/os-release file has not been updated on the V1.2.5. This should also be changed to lessen the confusion. :-) 

root@ZimaCube:/DATA/rauc/releases/v1.2.5# cat /etc/os-release 
NAME="ZimaOS"
BOARD="ZimaCube"
VERSION="v1.1.0"
ID=zimaos
VERSION_ID=1.1.0
PRETTY_NAME="ZimaOS v1.1.0"
CPE_NAME=cpe:2.3:o:icewhale:zimaos:1.1.0:*:development:*:*:*:zimacube:*
VARIANT="ZimaOS ZimaCube"
VARIANT_ID=zimacube
SUPERVISOR_MACHINE=ZimaCube
SUPERVISOR_ARCH=amd64
BUILD_DATE="2024/03/14 03:53:11 UTC"
MANUFACTURER="IceWhale Technology"
MODEL=ZimaCube

**Comment by LinkLeong** [comment]
can refer to #5
