### ISSUE TITLE
Change the root password and disable the SSH password to log in

### ISSUE THREAD

**Issue by Payton443** [IceWhaleTech/ZimaOS#23]
How do I change the root password and disable the ssh password login of ZimaOS? If it can't be modified, the system is very insecure

**Comment by thor9898** [comment]
+1 Also interested in this.

**Comment by raller1028** [comment]
Sorry, it's not supported at the moment.

**Comment by thor9898** [comment]
Is this even a priority?
Is there any version being developed where we might be able to do that?

**Comment by ShieldNavalny** [comment]
It's really a very major security issue. Can't we get a passwd or something like that in a distro?

**Comment by raller1028** [comment]
In the open-beta stage, we set the default root password and enable ssh convenience test, after the official release ssh will be disabled by default, the password can also be changed.

**Comment by aravhawk** [comment]
What is the SSH username and password?
