### ISSUE TITLE
[用户界面] v1.2全新引导界面建议

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/ZimaOS#63]
全新安装1.2后，默认引导页 UED 不是很美观，我简单修改了一下给个原型供参考。主要是左上角字体行距太挤，文字间宽度也稍微有点紧。右侧留白太多。

![before](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/7cb1dd03-ec07-4872-a04c-8c7ec7a4b1da)
![after](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/5303817f-7526-47f1-b358-638961a06938)

**Comment by Marrrrrrrrry** [comment]
该图是目前1.2的实机截图
![无标题](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/77e2e235-72ce-4b1f-9ec2-b2f8c56e3a17)

**Comment by ACMERUINLEO** [comment]
感谢你的反馈，左上角字体视觉上显挤是中文字体回退的原因，会在后续版本择期修复。如果在当前使用中依旧觉得不舒服的话可以尝试切到英文看一下。
