### ISSUE TITLE
安装时提示Disabling IRQ#16，卡住不动了

### ISSUE THREAD

**Issue by cheneylaw** [IceWhaleTech/ZimaOS#68]
![微信图片_20240523172214](https://github.com/IceWhaleTech/zimaos-rauc/assets/35223665/711c28ab-dead-4968-9b2e-70595644f13f)

**Comment by jerrykuku** [comment]
可以提供下硬件的具体信息么？

**Comment by LinkLeong** [comment]
Thanks for the feedback, due to the long stagnation we will close the issue and reopen it if necessary.
