### ISSUE TITLE
[bug report] smb 共享结束不了

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/ZimaOS#76]
v1.2.1 中，发现 zima 中结束了对文件夹的共享后，已挂载电脑依然可以访问该文件夹，而且可以解除挂载后重新挂载上
该 bug 只能在 zima 每次重启后失效
但可以稳定复现，也就是每次想彻底结束共享都要重启 zima

**Comment by orca-zhang** [comment]
v1.2.3处理了该问题，变更SMB权限时，会将当前操作Share的已有会话关闭，请再验证一下。
