### ISSUE TITLE
zima installer 安装遇到问题

### ISSUE THREAD

**Issue by thriken** [IceWhaleTech/ZimaOS#86]
用balenaEtcher-Portable-1.18.11 将zimaos_zimacube-1.2.2_installer.img 写入了32G U盘
目标系统是一体机主板 I5-4310U +4g+ msata 64GB + 1T HDD X2 
用U盘启动之后选择 安装zima ，选择msata之后报错
![121](https://github.com/user-attachments/assets/4178244b-a789-4a03-9c5d-8b0613e8d5ac)

**Comment by thriken** [comment]
Warning! Unable to generate a proper UUID! Creating an improper one as a last
resort! Windows 7 may crash if you save this partition table!


查询搜索引擎之后，据说是[gptfdisk](https://github.com/samangh/gptfdisk) 版本问题

**Comment by jerrykuku** [comment]
此问题应该在最近的installer中修复了，欢迎测试。

**Comment by LinkLeong** [comment]
Our 1.2.5 has been released and is ready for testing.
