### ISSUE TITLE
Feature Request: Configurable power button

### ISSUE THREAD

**Issue by gjchester** [IceWhaleTech/ZimaOS#89]
The default power button shuts done the Zima Cube, and the physical hardware does not protect the switch in any way, (such as the switch being slightly recessed) so its possible to press the switch while the cube is use by mistake.

Please consider a feature request to allow some user configutation of the power switch.

Options could be:

Short press does nothing, long (2 seconds plus) triggers an action.

Action could be shutdown, hibernate, sleep (depending on what the hardware can support), or even do nothing.

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have discussed this within our team and will not be offering this feature for the time being, thank you again for your feedback.
