### ISSUE TITLE
ZimaOS Takes too long to shutdown

### ISSUE THREAD

**Issue by ProtocolNebula** [IceWhaleTech/ZimaOS#91]
When shutdown, ZimaOS requires a lot of time to power off.

Any clue about why this happens? Is related to the OS, HDD, wrong OS setup...?

![tale_too_long](https://github.com/user-attachments/assets/348c6f78-1408-4af1-b817-21673a5bbac6)

**Comment by jerrykuku** [comment]
Perhaps smartctl, the service that detects the health of the drive, is blocking the shutdown. We will check this out, thanks for the feedback.

**Comment by LinkLeong** [comment]
We have optimized the issue, please verify with the latest version.
