### ISSUE TITLE
ZimaOS Doesn't Support iSCSI Volumes

### ISSUE THREAD

**Issue by haplopeart** [IceWhaleTech/ZimaOS#95]
I am somewhat disappointed that ZimaOS doesn't support making the Storage space on its drives available as iSCSI volumes. This is a common NAS functionality.  ISCSI is generally much faster than SMB/CIFS.  It also allows the volumes to be directly mounted as drives on the connected (Windows/Linux/MAC) operating system.  This in turn makes backups simpler particularly with some backup services which do not allow for backing up drives on the host system that are mounted as SMB shares (BackBlaze).

**Comment by jerrykuku** [comment]
We are investigating iSCSI support, but are currently experiencing some difficulties integrating targetcli into the system. Please wait some more time.

**Comment by Lukasneo** [comment]
Would really appreciate if Zimaos would support ISCSI

**Comment by LinkLeong** [comment]
You can use the
https://www.zimaspace.com/docs/zimaos/iSCSI-usage-tutorial tutorial to complete the iSCSI operation.
