### ISSUE TITLE
ZFS无法挂载

### ISSUE THREAD

**Issue by NekoLines** [IceWhaleTech/ZimaOS#97]
当前版本是v1.2.4
当我尝试执行命令挂载在debian下创建的ZFSPool时报错：
```
root@ZimaCube:/usr/lib# zpool import -f  pool_name
This pool uses the following feature(s) not supported by this system:
	com.klarasystems:vdev_zaps_v2
cannot import 'pool_name': unsupported version or feature
```
尝试使用只读模式挂载提示相同。检查[这个链接](https://openzfs.github.io/openzfs-docs/Basic%20Concepts/Feature%20Flags.html)，发现是zfs版本偏低导致的。需要zfs版本2.2.5才支持该特性。尝试自己手动更新，但是没有包管理器也不支持基础库所以失败。望后续更新。

**Comment by jerrykuku** [comment]
下个版本将更新到2.2.5,敬请期待。

**Comment by LinkLeong** [comment]
v1.2.5 has been released and is ready for testing.
