### ISSUE TITLE
ZimaOS App Store: 3rd party repository refresh option

### ISSUE THREAD

**Issue by axelquack** [IceWhaleTech/ZimaOS#98]
Hi - when I add a third-party repository in the App Store (zip) file, and the original does source adds new applications, the only way to show these within the UI is to do a reboot. Would you be so kind to either add a refresh button of the original source? Or describe where to do that manully via terminal/ssh session?
Also removing and adding the zip file does not help without a restart of the OS.

Thanks!

**Comment by CorrectRoadH** [comment]
Thanks for your feedback. another way is wait 10 mins. ZimaOS every 10 min will fetch the repository

**Comment by axelquack** [comment]
Hi @CorrectRoadH - I have to admit, I don't know how it is pulled together e.g. you run a cron-job; I can only say that with my two different Cubes it only sometimes works. They are on 24/7. I can't find any pattern that would explain the rationale, but sometimes it is not updating for days/weeks.
